# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
