# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=16)),
                ('datetime', models.DateTimeField(default='')),
            ],
        ),
    ]
