# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_execel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='execel',
            name='phone',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
